require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NotecollectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Notecollection. As you add validations to Notecollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotecollectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all notecollections as @notecollections" do
      notecollection = Notecollection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:notecollections).should eq([notecollection])
    end
  end

  describe "GET show" do
    it "assigns the requested notecollection as @notecollection" do
      notecollection = Notecollection.create! valid_attributes
      get :show, {:id => notecollection.to_param}, valid_session
      assigns(:notecollection).should eq(notecollection)
    end
  end

  describe "GET new" do
    it "assigns a new notecollection as @notecollection" do
      get :new, {}, valid_session
      assigns(:notecollection).should be_a_new(Notecollection)
    end
  end

  describe "GET edit" do
    it "assigns the requested notecollection as @notecollection" do
      notecollection = Notecollection.create! valid_attributes
      get :edit, {:id => notecollection.to_param}, valid_session
      assigns(:notecollection).should eq(notecollection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Notecollection" do
        expect {
          post :create, {:notecollection => valid_attributes}, valid_session
        }.to change(Notecollection, :count).by(1)
      end

      it "assigns a newly created notecollection as @notecollection" do
        post :create, {:notecollection => valid_attributes}, valid_session
        assigns(:notecollection).should be_a(Notecollection)
        assigns(:notecollection).should be_persisted
      end

      it "redirects to the created notecollection" do
        post :create, {:notecollection => valid_attributes}, valid_session
        response.should redirect_to(Notecollection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notecollection as @notecollection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Notecollection.any_instance.stub(:save).and_return(false)
        post :create, {:notecollection => {  }}, valid_session
        assigns(:notecollection).should be_a_new(Notecollection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Notecollection.any_instance.stub(:save).and_return(false)
        post :create, {:notecollection => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested notecollection" do
        notecollection = Notecollection.create! valid_attributes
        # Assuming there are no other notecollections in the database, this
        # specifies that the Notecollection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Notecollection.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => notecollection.to_param, :notecollection => { "these" => "params" }}, valid_session
      end

      it "assigns the requested notecollection as @notecollection" do
        notecollection = Notecollection.create! valid_attributes
        put :update, {:id => notecollection.to_param, :notecollection => valid_attributes}, valid_session
        assigns(:notecollection).should eq(notecollection)
      end

      it "redirects to the notecollection" do
        notecollection = Notecollection.create! valid_attributes
        put :update, {:id => notecollection.to_param, :notecollection => valid_attributes}, valid_session
        response.should redirect_to(notecollection)
      end
    end

    describe "with invalid params" do
      it "assigns the notecollection as @notecollection" do
        notecollection = Notecollection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Notecollection.any_instance.stub(:save).and_return(false)
        put :update, {:id => notecollection.to_param, :notecollection => {  }}, valid_session
        assigns(:notecollection).should eq(notecollection)
      end

      it "re-renders the 'edit' template" do
        notecollection = Notecollection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Notecollection.any_instance.stub(:save).and_return(false)
        put :update, {:id => notecollection.to_param, :notecollection => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notecollection" do
      notecollection = Notecollection.create! valid_attributes
      expect {
        delete :destroy, {:id => notecollection.to_param}, valid_session
      }.to change(Notecollection, :count).by(-1)
    end

    it "redirects to the notecollections list" do
      notecollection = Notecollection.create! valid_attributes
      delete :destroy, {:id => notecollection.to_param}, valid_session
      response.should redirect_to(notecollections_url)
    end
  end

end
